# Generated by Django 5.2.9 on 2026-01-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Django_App", "0002_alter_customuser_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="finishDate",
            field=models.DateField(),
        ),
    ]
